apiVersion: v1
kind: Pod
metadata:
  name: pod-privileged
  namespace: audit-zone
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command: ["sleep", "3600"]
    securityContext:
      privileged: true