apiVersion: v1
kind: Pod
metadata:
  name: pod-root-user
  namespace: audit-zone
spec:
  containers:
  - name: nginx
    image: nginx:latest
    command: ["sleep", "3600"]
    securityContext:
      runAsUser: 0
      runAsGroup: 0
      runAsNonRoot: false
      readOnlyRootFilesystem: false