apiVersion: v1
kind: ServiceAccount
metadata:
  name: analyst-sa
  namespace: propdevelopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: developer-sa
  namespace: propdevelopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: engineer-sa
  namespace: propdevelopment
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-sa
  namespace: propdevelopment