apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: analyst-binding
subjects:
- kind: ServiceAccount
  name: analyst-sa
roleRef:
  kind: Role
  name: analyst-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: developer-binding
subjects:
- kind: ServiceAccount
  name: developer-sa
roleRef:
  kind: Role
  name: developer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: engineer-binding
subjects:
- kind: ServiceAccount
  name: engineer-sa
roleRef:
  kind: Role
  name: engineer-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-binding
subjects:
- kind: ServiceAccount
  name: devops-sa
roleRef:
  kind: Role
  name: devops-role
  apiGroup: rbac.authorization.k8s.io