apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sPropRequireNonRoot
metadata:
  name: prevent-root-user
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    namespaces: ["audit-zone"]
  parameters:
    message: "Containers must run as non-root users"